### ISSUE TITLE
A Bug...

### ISSUE THREAD

**Issue by SharkFinPro** [AJS-development/OpenAgar#35]
[OpenAgar] Server succesfully created
>
[OpenAgar] Killed all processes
C:\Users\Atomix\Desktop\OpenAgar-master\source\core\Player.js:164
        this.cells.clear();
                   ^

TypeError: this.cells.clear is not a function
    at Player.reset (C:\Users\Atomix\Desktop\OpenAgar-master\source\core\Player.js:164:20)
    at Player.changeServers (C:\Users\Atomix\Desktop\OpenAgar-master\source\core\Player.js:157:14)
    at socketService.<anonymous> (C:\Users\Atomix\Desktop\OpenAgar-master\source\core\socketService.js:240:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at C:\Users\Atomix\Desktop\OpenAgar-master\node_modules\socket.io\lib\socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Press any key to exit...

someone gave me that, after i had gotten one and closed out of my server. This Is a BUG

**Comment by Atomix23** [comment]
It sees its me boi!

**Comment by Andrews54757** [comment]
@SharkFinPro . do `npm install`
