### ISSUE TITLE
`set` undefined

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/OpenAgar#66]
Thought i'd just document this. 

```
Cannot read property 'set' of undefined
TypeError: Cannot read property 'set' of undefined
    at Grid.insert (C:\Users\LegitSoulja\Documents\OpenAgar\node_modules\hashbounds\Grid.js:112:30)
    at HashBounds.insert (C:\Users\LegitSoulja\Documents\OpenAgar\node_modules\hashbounds\index.js:67:42)
    at HashBounds.update (C:\Users\LegitSoulja\Documents\OpenAgar\node_modules\hashbounds\index.js:59:14)
    at WorldModel.update (C:\Users\LegitSoulja\Documents\OpenAgar\source\core\worldModel.js:87:20)
    at Main.updateHash (C:\Users\LegitSoulja\Documents\OpenAgar\source\core\main.js:1229:25)
    at upt.forEach (C:\Users\LegitSoulja\Documents\OpenAgar\source\core\main.js:1210:18)
    at Array.forEach (native)
    at Main.updatePlayerNodes (C:\Users\LegitSoulja\Documents\OpenAgar\source\core\main.js:1208:13)
    at Main.mloop (C:\Users\LegitSoulja\Documents\OpenAgar\source\core\main.js:1078:18)
    at Main.<anonymous> (C:\Users\LegitSoulja\Documents\OpenAgar\source\core\main.js:1062:18)

```

**Comment by Andrews54757** [comment]
Is your hashbounds version 4.2.2?

**Comment by SharkFinPro** [comment]
@Andrews54757 
What is your email

**Comment by LegitSoulja** [comment]
@SharkFinPro it's everywhere to be found. 

> http://home.opnagar.us

@Andrews54757  And yes

**Comment by SharkFinPro** [comment]
Ok

**Comment by SharkFinPro** [comment]
@LegitSoulja BTW can I have Administrator on the site?

**Comment by LegitSoulja** [comment]
@SharkFinPro not so fast. You should probably learn how IPS works. It's not a toy, as of xenforo.

I'll let you moderate the content for now. However, other stuff is too advanced for you.

**Comment by SharkFinPro** [comment]
Ok

**Comment by SharkFinPro** [comment]
@Andrews54757 I got one of these too...but it said delete not set

**Comment by SharkFinPro** [comment]
or remove

**Comment by SharkFinPro** [comment]
something liek that
