### ISSUE TITLE
Choose something else to play 

### ISSUE THREAD

**Issue by ghost** [AJS-development/OpenAgar#96]
fs.js:143
    throw new ERR_INVALID_CALLBACK(cb);
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at makeCallback (fs.js:143:11)
    at Object.mkdir (fs.js:810:14)
    at Log.setup (winBullShit\Ogar-Unlimited-master\src\modules\log.js:14:8)
    at GameServer.start (winBullShit\Ogar-Unlimited-master\src\core\GameServer.js:232:14)
    at ControlServer.start (winBullShit\Ogar-Unlimited-master\src\core\ControlServer.js:60:21)
    at Multiverse.create (winBullShit\Ogar-Unlimited-master\src\core\Multiverse.js:87:7)
    at Multiverse.init (winBullShit\Ogar-Unlimited-master\src\core\Multiverse.js:130:26)
    at Object.<anonymous> (winBullShit\Ogar-Unlimited-master\src\index.js:38:12)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10) {
  code: 'ERR_INVALID_CALLBACK'
}
Thanks Guys

**Comment by Cabotrez** [comment]
I don't think someone will help you, because this project was closed

**Comment by ismaillabiade** [comment]
:/ thanks

**Comment by ismaillabiade** [comment]
Thank you !

**Comment by Cabotrez** [comment]
ok
